version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpBlog
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 6M
  
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - '80:80'
    restart: always
    volumes:
      - './blog:/var/www/html:rw'
    environment:
      - WORDPRESS_DB_HOST=DB:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    networks:
      - wpBlog
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 6M

networks:
  wpBlog:

volumes:
  db_data: